name: Stang Gappa
favicon: null
layout_spectrum: 0
typography_spectrum: 0.69177
title: Strategy and Marketing for the Small Business Warrior
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdccce'
    - '#023467'
    - '#ffcd07'
    - '#ffffff'
    - '#a1a1a1'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
