name: Stang Gappa
favicon: null
layout_spectrum: 0.48792
typography_spectrum: 0.69177
title: Strategy and Marketing for Sustainable Growth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#56bffe'
    - '#50525b'
    - '#9b0303'
    - '#cc4e02'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
