name: Stang Gappa
favicon: null
layout_spectrum: 0
typography_spectrum: 0.69177
title: Strategy and Marketing for the Small Business Warrior
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9dbec5'
    - '#30679d'
    - '#262c2a'
    - '#cbc869'
    - '#d5ede3'
  brandStrength: 1
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
